# Generated by Django 4.2.2 on 2023-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_category', models.CharField(choices=[('hardware', 'hardware'), ('software', 'software'), ('instrument', 'instrument')], max_length=50)),
            ],
        ),
    ]
