# Generated by Django 4.2.1 on 2023-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
            ],
        ),
    ]
