# Generated by Django 4.2.2 on 2023-06-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productcategory_products_delete_react'),
    ]

    operations = [
    ]
