# Generated by Django 4.2.2 on 2023-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('value1', 'Label 1'), ('value2', 'Label 2'), ('value3', 'Label 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
